CREATE DATABASE ECommerce_Online_Retail;


CREATE OR REPLACE TABLE online_retail (
  InvoiceNo STRING,
  StockCode STRING,
  Description STRING,
  Quantity STRING,
  InvoiceDate STRING,
  UnitPrice STRING,
  CustomerID STRING,
  Country STRING
);

INSERT INTO online_retail VALUES
('10001','85123A','WHITE HANGING HEART T-LIGHT HOLDER',6,'2010-12-01 08:26:00',2.55,'17850','United Kingdom'),
('10002','71053','WHITE METAL LANTERN',6,'2010-12-01 08:28:00',3.39,'17850','United Kingdom'),
('10003','84406B','CREAM CUPID HEARTS COAT HANGER',8,'2010-12-01 08:34:00',2.75,'13047','United Kingdom'),
('10004','84029G','KNITTED UNION FLAG HOT WATER BOTTLE',6,'2010-12-01 08:35:00',3.39,'13047','United Kingdom'),
('10005','22752','SET 7 BABUSHKA NESTING BOXES',2,'2010-12-01 08:45:00',7.65,'12583','France'),
('10006','21730','GLASS STAR FROSTED T-LIGHT HOLDER',6,'2010-12-01 09:00:00',4.25,'13748','Germany'),
('10007','22633','HAND WARMER UNION JACK',6,'2010-12-01 09:15:00',1.85,'15100','Spain'),
('10008','84879','ASSORTED COLOUR BIRD ORNAMENT',32,'2010-12-01 09:30:00',1.69,'14688','Netherlands'),
('10009','22423','REGENCY CAKESTAND 3 TIER',3,'2010-12-01 09:45:00',12.75,'16029','Belgium'),
('10010','47566','PARTY BUNTING',6,'2010-12-01 10:00:00',4.95,'12433','Italy');

CREATE OR REPLACE TABLE online_retail AS
SELECT
  InvoiceNo,
  StockCode,
  Description,
  TRY_TO_NUMBER(Quantity) AS Quantity,
  TRY_TO_TIMESTAMP(InvoiceDate) AS InvoiceDate,
  TRY_TO_DOUBLE(UnitPrice) AS UnitPrice,
  CustomerID,
  Country
FROM online_retail_stage;


DELETE FROM online_retail
WHERE Quantity IS NULL
   OR UnitPrice IS NULL
   OR InvoiceDate IS NULL;

//Find the total number of orders
USE ECOMMERCE_ONLINE_RETAIL;
SELECT COUNT(DISTINCT InvoiceNo)AS TOTAL_ORDERS
FROM ONLINE_RETAIL;

//Calculate total revenue
SELECT SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE
FROM ONLINE_RETAIL;

//List all unique countries
SELECT DISTINCT COUNTRY
FROM ONLINE_RETAIL;

//Find the total number of customers
SELECT COUNT(DISTINCT CUSTOMERID)
FROM ONLINE_RETAIL;

//List all unique products
SELECT DISTINCT DESCRIPTION
FROM ONLINE_RETAIL;

//Calculate total revenue for each country
SELECT SUM(UNITPRICE * QUANTITY) AS TOTAL_REVANUE,COUNTRY
FROM ONLINE_RETAIL
GROUP BY COUNTRY
ORDER BY TOTAL_REVANUE;

//Top 3 customers based on total spending
SELECT CUSTOMERID , SUM(UNITPRICE * QUANTITY) AS TOTAL_SPENDING
FROM ONLINE_RETAIL
GROUP BY CUSTOMERID
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;

//Find top 5 products based on quantity sold
SELECT DESCRIPTION , SUM(QUANTITY) AS SOLD
FROM ONLINE_RETAIL
GROUP BY DESCRIPTION
ORDER BY SOLD DESC
LIMIT 5;

//Calculate total revenue for each product
SELECT SUM(UNITPRICE * QUANTITY)AS TOTAL_REVANUE, DESCRIPTION 
FROM ONLINE_RETAIL
GROUP BY DESCRIPTION;

//Find the average order value
SELECT SUM(QUANTITY * UNITPRICE)/COUNT(DISTINCT INVOICENO)
FROM ONLINE_RETAIL;

//Show monthly sales trend
SELECT DATE_TRUNC('month', InvoiceDate) AS month,
       SUM(Quantity * UnitPrice) AS total_revenue
FROM online_retail
GROUP BY month
ORDER BY month;

//Rank customers based on total spending
SELECT CUSTOMERID,SUM(QUANTITY * UNITPRICE) AS TOTAL_SPENDING,
DENSE_RANK()OVER ( ORDER BY SUM(QUANTITY * UNITPRICE) DESC) AS RNK
FROM ONLINE_RETAIL
GROUP BY CUSTOMERID
ORDER BY TOTAL_SPENDING DESC
;
